# @url = "localhost:5500"

### user register
POST http://localhost:5500/api/users/register HTTP/1.1
Content-Type: application/json

{
  "name": "小明",
  "account": "xiaoming233",
  "password": "Xm123456",
  "description": "我是小明",
  "avatar": null
}

### user login
POST http://localhost:5500/api/users/login HTTP/1.1
Content-Type: application/json

{
  "account": "xiaoming233",
  "password": "Xm123456"
}

### upload avatar
POST http://localhost:5500/api/users/upload/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDI4NzhhODRmZTNmYTk3MmRjNjhjZTgiLCJpYXQiOjE2ODA0Mjk0MjYsImV4cCI6MTY4MTI5MzQyNn0.R6GkSjTrHdQOjIhGMQi5ORujfUqdH3RQPm5_rNTcb6A

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW
Accept-Encoding:multipart/form-data

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="1.jpg"
Content-Type: image/jpeg
< ./1.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW--